# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='img_src',
            field=models.CharField(max_length=255),
        ),
    ]
