# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=50)),
                ('p', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'recommend',
            },
        ),
    ]
