# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
