# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_timegoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
